import React from 'react';
import { LegalDocumentPage } from './LegalDocumentPage';

export const PrivacyPolicyPage: React.FC = () => (
  <LegalDocumentPage title="Privacy Policy" icon="privacy">
    <p><strong>Effective date:</strong> 4 September 2026</p>
    <p className="mt-5">This Privacy Policy explains how Turnaround Logistics Systems (“Turnaround”, “we”, “us”) collects, uses, stores, shares, and protects information when you use the Turnaround fleet operations platform and related services.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">1. Who is responsible</h2>
    <p className="mt-2">Turnaround operates the platform. Your employer, customer, or other organisation that invited you controls the operational data in its workspace. For questions about fleet, driver, trip, or company records, contact your workspace administrator first. For privacy requests to Turnaround, contact privacy@turnaround.io.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">2. Information we collect</h2>
    <ul className="mt-2 list-disc space-y-2 pl-5"><li>Account information such as name, work email, role, phone number, organisation, authentication records, and preferences.</li><li>Company information such as legal details, contact information, operating locations, billing settings, logo, and configured policies.</li><li>Fleet and operational information such as vehicle registrations, specifications, driver details, trips, routes, cargo references, gate passes, dwell events, and status updates.</li><li>Location and telemetry information such as GPS coordinates, timestamps, geofences, speed, arrival, departure, and related measurements from connected systems.</li><li>Technical and usage information such as IP address, device and browser details, session records, audit events, error logs, and actions taken in the platform.</li><li>Communications, support requests, and information provided during account or service enquiries.</li></ul>
    <h2 className="mt-8 text-lg font-bold text-text-primary">3. How we use information</h2>
    <p className="mt-2">We use information to provide and secure the service; authenticate users and enforce company roles; monitor vehicles, trips, terminals, gate passes, and delays; calculate dwell, turnaround, cost, and demurrage indicators; deliver notifications selected by a workspace; provide support; maintain backups and audit trails; detect fraud, misuse, and security incidents; improve reliability and aggregated analytics; and comply with law or protect people and property.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">4. Legal bases and permissions</h2>
    <p className="mt-2">Where required by law, processing is based on contract, legitimate interests, consent, legal obligations, or protection of vital interests. Organisations are responsible for giving required notices and obtaining permissions for driver, employee, vehicle, GPS, contact, and cargo data they submit.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">5. Sharing and international processing</h2>
    <p className="mt-2">We may share information with hosting, authentication, mapping, telematics, messaging, analytics, payment, security, and support providers; professional advisers; regulators or law enforcement when legally required; and a successor in a merger or asset transaction. Providers receive only the access needed for their service and information may be processed in other countries with safeguards required by applicable law. We do not sell personal information.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">6. Retention and security</h2>
    <p className="mt-2">We retain information for the service relationship, configured company retention needs, legal and accounting obligations, dispute resolution, fraud prevention, and legitimate business records. We use access controls, role permissions, encryption in transit, session protection, monitoring, backups, and audit logging. No service is completely secure, so protect credentials and report suspected compromise promptly.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">7. Cookies and rights</h2>
    <p className="mt-2">We use essential cookies and browser storage for authentication, security, preferences, and performance. Subject to applicable law, you may request access, correction, deletion, restriction, objection, portability, or withdrawal of consent. We may verify identity, apply lawful exceptions, and coordinate with your workspace administrator. You may also complain to your local data protection authority.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">8. Children, changes, and contact</h2>
    <p className="mt-2">The service is for business users and is not directed to children. We may update this policy by publishing a revised effective date and, where required, providing notice. Contact privacy@turnaround.io for privacy requests and security@turnaround.io for suspected security incidents.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">9. Workspace administration and access</h2>
    <p className="mt-2">Workspace administrators control invitations, roles, permissions, company settings, connected providers, and access to operational records. Administrators may view or manage information submitted by members of their workspace. We may retain access logs showing who viewed, created, changed, exported, or deleted records in order to protect the workspace and investigate incidents.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">10. Location and driver information</h2>
    <p className="mt-2">GPS and geofence information can reveal vehicle movements, work patterns, routes, and visits to facilities. Organisations must use the platform transparently, limit tracking to legitimate operational purposes, configure appropriate retention, and comply with employment, transport, telecommunications, and data protection requirements. Turnaround does not independently determine an organisation’s lawful basis for employee monitoring.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">11. Automated insights and profiling</h2>
    <p className="mt-2">The service may compare dwell times, routes, costs, delays, and operational patterns to generate alerts, scores, forecasts, recommendations, and reports. These outputs may be incomplete or incorrect because they depend on submitted data, connectivity, device quality, configuration, and statistical assumptions. Organisations should provide human review and a process for correcting inaccurate records before making consequential decisions.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">12. Security incidents</h2>
    <p className="mt-2">If we identify a security incident affecting personal information, we will assess it, contain it, preserve relevant evidence, and provide notices to customers or authorities when required by law. Users must report suspected compromise, lost devices, unauthorised access, or accidental disclosure promptly and must not test security controls against production systems without written permission.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">13. Requests and verification</h2>
    <p className="mt-2">Send privacy requests with enough information for us to identify the relevant account or workspace. We may ask for identity verification, clarify the request, charge a lawful administrative fee, or refuse a request where a legal exception applies. Requests concerning a company’s operational records may need to be handled by that company as controller or business owner.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">14. Data deletion and portability</h2>
    <p className="mt-2">When an account or workspace is closed, information may remain in backups, audit records, legal holds, aggregated statistics, or records that another customer is entitled to retain. Subject to law and the customer agreement, we support reasonable export and deletion requests through authorised workspace administrators. Deleted content may not be recoverable.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">15. Regional terms</h2>
    <p className="mt-2">Additional rights or obligations may apply under the laws of Kenya or another jurisdiction where you or your organisation operates. Where this policy conflicts with a mandatory local requirement, the mandatory requirement prevails. Nothing in this policy removes a right that cannot lawfully be waived.</p>
  </LegalDocumentPage>
);
