import React from 'react';
import { LegalDocumentPage } from './LegalDocumentPage';

export const TermsOfServicePage: React.FC = () => (
  <LegalDocumentPage title="Terms and Conditions" icon="terms">
    <p><strong>Effective date:</strong> 4 September 2026</p>
    <p className="mt-5">These Terms govern access to the Turnaround fleet operations platform and related services. By accessing the service, you confirm that you are authorised to do so and agree to these Terms. If you act for an organisation, you represent that you can bind it.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">1. The service</h2>
    <p className="mt-2">Turnaround provides tools for fleet operations, GPS and geofence monitoring, trip and route coordination, dwell analysis, gate-pass management, notifications, reporting, cost indicators, and operational intelligence. Features may change as the service develops. The service supports decisions but does not replace professional judgement, driver safety procedures, customs or legal advice, emergency services, or regulatory compliance.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">2. Accounts, companies, and access</h2>
    <p className="mt-2">Provide accurate information, keep credentials confidential, use your own account, and promptly report suspected unauthorised access. A public signup creates a separate company workspace and its first account is the workspace administrator. Administrators may invite, assign, suspend, or remove users. Do not attempt to join or access another company without authorisation, bypass role permissions, or share accounts.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">3. Customer responsibilities</h2>
    <ul className="mt-2 list-disc space-y-2 pl-5"><li>Keep company, vehicle, route, driver, cargo, and location data accurate and lawful.</li><li>Obtain required notices, consents, licences, and permissions for tracking and notifications.</li><li>Maintain safe loading, driving, customs, emergency, and operational procedures independently of the service.</li><li>Review alerts, calculations, predictions, route information, and recommendations before acting on them.</li><li>Maintain suitable devices, connectivity, telematics equipment, and third-party accounts.</li><li>Use company data only for legitimate business purposes and protect confidential information.</li></ul>
    <h2 className="mt-8 text-lg font-bold text-text-primary">4. Acceptable use</h2>
    <p className="mt-2">You must not use the service unlawfully; infringe rights; upload malware or harmful content; disrupt, probe, scan, reverse engineer, or decompile it except where law permits; evade security or usage limits; access another tenant; submit fraudulent, discriminatory, abusive, defamatory, or unrelated content; or rely on the service alone for safety-critical decisions.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">5. Data, privacy, and integrations</h2>
    <p className="mt-2">Your organisation retains rights in data it submits. You grant Turnaround the limited rights required to host, process, transmit, display, back up, secure, and improve the service as instructed and described in the Privacy Policy. Mapping, telematics, messaging, payment, hosting, and authentication integrations may have separate terms and outages outside Turnaround’s control.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">6. Availability, support, and fees</h2>
    <p className="mt-2">We aim for reliable availability but do not promise uninterrupted or error-free service. Maintenance, connectivity, third-party failures, security events, and circumstances beyond reasonable control may affect it. Fees, plans, refunds, taxes, and payment terms are governed by the applicable order, subscription, or written agreement.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">7. Intellectual property and confidentiality</h2>
    <p className="mt-2">Turnaround and its licensors retain rights in the software, designs, documentation, trademarks, and technology. Except for the limited right to use the service under these Terms, no rights transfer. Each party must protect non-public information received from the other and use it only for the relationship, subject to lawful disclosure and standard confidentiality exceptions.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">8. Suspension and termination</h2>
    <p className="mt-2">We or your organisation may suspend or terminate access for breach, overdue fees, security or legal risk, misuse, or discontinuation. On termination, access may end and data may be deleted according to the applicable agreement, retention requirements, and law.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">9. Disclaimers, liability, and indemnity</h2>
    <p className="mt-2">To the fullest extent permitted by law, the service is provided “as available” and we do not guarantee that GPS data, alerts, predictions, routes, costs, or reports are complete, accurate, timely, or fit for a particular purpose. We are not liable for indirect, incidental, special, consequential, exemplary, or punitive loss, or loss of profit, revenue, data, business, or goodwill. You agree to defend and indemnify Turnaround and its personnel against claims arising from your unlawful use, breach, or submitted data, to the extent permitted by law.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">10. Changes, law, and contact</h2>
    <p className="mt-2">We may update these Terms by publishing a revised effective date and providing notice where required. Continued use after the effective date constitutes acceptance where permitted by law. These Terms are governed by the laws applicable to the contracting entity and the parties’ written agreement; disputes will be handled by the competent courts unless otherwise agreed. Contact legal@turnaround.com for questions.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">11. Workspace ownership and administration</h2>
    <p className="mt-2">The person who creates a workspace represents that they are authorised to establish it for the named organisation. The creating account is the initial administrator and is responsible for inviting members, assigning appropriate roles, reviewing access, and maintaining accurate company settings. An administrator may transfer administrative control where the product supports that function.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">12. Operational data and tracking consent</h2>
    <p className="mt-2">You must have the right to submit vehicle, driver, employee, customer, cargo, route, and location information. You are responsible for informing affected people about GPS monitoring, obtaining required consents or other permissions, and honouring applicable transport, employment, privacy, customs, and safety rules. Turnaround is a service provider and does not authorise unlawful monitoring.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">13. Automated calculations</h2>
    <p className="mt-2">Dwell calculations, cost estimates, demurrage indicators, route benchmarks, risk scores, alerts, and recommendations are decision-support outputs. They depend on data quality, timestamps, GPS availability, configured thresholds, third-party services, and statistical assumptions. You must validate outputs and retain appropriate human oversight, particularly for employment, safety, compliance, or financial decisions.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">14. Security and responsible disclosure</h2>
    <p className="mt-2">You must protect credentials, use supported software, restrict access to authorised personnel, and notify us of suspected security issues. Do not conduct penetration tests, load tests, scraping, or vulnerability research against the service without prior written approval. We may suspend access immediately where activity threatens users, data, infrastructure, or a third party.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">15. Records, exports, and deletion</h2>
    <p className="mt-2">You are responsible for maintaining independent copies of records needed for your business. Export and deletion features may be subject to permissions, technical limits, legal holds, backup cycles, retention obligations, and the rights of other users or customers. Deleted records may not be recoverable and termination does not automatically erase records required by law.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">16. Notices and electronic communications</h2>
    <p className="mt-2">You agree that service notices may be delivered through the platform, to an account email, or through an administrator. You must keep contact information current and monitor notices. Electronic records and approvals may be used to evidence activity and agreements where legally valid.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">17. Force majeure and severability</h2>
    <p className="mt-2">Neither party is responsible for delay caused by events beyond reasonable control, including infrastructure failure, telecommunications outages, natural disasters, civil disruption, public-health emergencies, labour disputes, or government action. If any provision is unenforceable, it will be limited to the minimum extent necessary and the remaining provisions will continue.</p>
    <h2 className="mt-8 text-lg font-bold text-text-primary">18. Entire agreement and waiver</h2>
    <p className="mt-2">These Terms, the Privacy Policy, and any applicable order or written agreement form the agreement for the service. A failure to enforce a provision is not a waiver of future enforcement. Terms intended by their nature to survive termination, including confidentiality, intellectual property, payment, disclaimers, liability, indemnity, and dispute provisions, will survive.</p>
  </LegalDocumentPage>
);
